WildCodeSchool/202209-orleans-php-project-originsdigital

assets/styles/_navbar.scss

Fixed the navbar to be responsive in all browsers

---

assets/styles/app.scss
assets/styles/user_profile.scss
composer.json
composer.lock
config/bundles.php
config/packages/twig.yaml
config/packages/vich_uploader.yaml
migrations/Version20230104160350.php
public/uploads/.gitignore
src/Controller/ProfileController.php
src/Entity/User.php
src/Form/UserType.php
symfony.lock
templates/base.html.twig
templates/profile/edit.html.twig
templates/profile/index.html.twig
webpack.config.js

Close #120, Close #121, Close #119, Close #123, Close #118

S02 us03 user profile (edit)

---

assets/styles/adminIndex.scss
assets/styles/app.scss
src/Controller/AdminVideoController.php
src/Form/VideoType.php
templates/adminVideo/_delete_form.html.twig
templates/adminVideo/_form.html.twig
templates/adminVideo/edit.html.twig
templates/adminVideo/index.html.twig
templates/adminVideo/new.html.twig
templates/adminVideo/show.html.twig
templates/components/_navbar_admin.html.twig

S03US11 - CRUD videos read

---

assets/styles/_adminIndex.scss
assets/styles/app.scss
src/Controller/AdminSponsorController.php
src/Form/SponsorType.php
templates/admin_sponsor/_delete_form.html.twig
templates/admin_sponsor/_form.html.twig
templates/admin_sponsor/edit.html.twig
templates/admin_sponsor/index.html.twig
templates/admin_sponsor/new.html.twig
templates/admin_sponsor/show.html.twig
templates/components/_navbar_admin.html.twig

S03US37_CRUD_sponsors_read

---

config/packages/vich_uploader.yaml
migrations/Version20230110204918.php
src/Controller/AdminSponsorController.php
src/Entity/Sponsor.php
src/Form/SponsorType.php
templates/admin_sponsor/_form.html.twig
templates/admin_sponsor/index.html.twig
templates/admin_sponsor/new.html.twig
templates/components/_sponsor.html.twig

S03US40 CRUD Sponsors ADD

---

templates/components/_sponsor.html.twig

S03US58 Update sponsors view

---

src/Form/VideoType.php
templates/adminVideo/_delete_form.html.twig
templates/adminVideo/edit.html.twig

S03US12B CRUD videos - Delete

---

src/Form/VideoType.php
templates/adminVideo/edit.html.twig

S03US12 CRUD Videos - Update 

---

templates/admin_cat/edit.html.twig

CRUD Categories - Update

---

templates/admin_cat/_delete_form.html.twig
templates/admin_cat/index.html.twig

S03US16 CRUD Categories - Delete

---

src/Controller/AdminCatController.php

FIX - Slug filled automatically in Categories

---

assets/app.js
migrations/Version20230123092207.php
package.json
src/Controller/VideoController.php
src/Entity/User.php
src/Entity/Video.php
templates/video/index.html.twig
yarn.lock

S04US06 Add Favorite Video

---

config/packages/vich_uploader.yaml
migrations/Version20230124162949.php
src/Entity/Category.php
src/Form/CategoryType.php

S04US70 Category Upload works - Twig render to come

---

assets/styles/categories.scss
templates/category/index.html.twig

S04US70 - Index Categories now with background pictures

---

src/Controller/ActualityController.php
src/Form/ActualityType.php
templates/actuality/_delete_form.html.twig
templates/actuality/_form.html.twig
templates/actuality/edit.html.twig
templates/actuality/index.html.twig
templates/actuality/new.html.twig
templates/actuality/show.html.twig
templates/components/_navbar_admin.html.twig

S04US73 add crud index of actuality

---

templates/bundles/TwigBundle/Exception/error403.html.twig
templates/bundles/TwigBundle/Exception/error404.html.twig
templates/bundles/TwigBundle/Exception/error500.html.twig

S04US72 Error Pages

---

migrations/Version20221215111540.php
src/Entity/Video.php
src/Form/VideoType.php
templates/adminVideo/_delete_form.html.twig
templates/adminVideo/_form.html.twig
templates/adminVideo/edit.html.twig
templates/adminVideo/index.html.twig
templates/adminVideo/show.html.twig

Fix - Admin Video

---

assets/styles/_adminIndex.scss
config/packages/vich_uploader.yaml
src/Controller/ActualityController.php
src/Entity/Actuality.php
src/Form/ActualityType.php
templates/actuality/_form.html.twig
templates/actuality/new.html.twig

S04US74 make crud with add banniere

---

templates/actuality/_delete_form.html.twig
templates/actuality/index.html.twig

S04US76 crud banniere - delete

---

templates/components/_navbar.html.twig

Fix place search link to nav

---

assets/styles/showCategories.scss
templates/category/show.html.twig

Fix category view empty

---

assets/styles/_flash_messages.scss

Fix position flash message

---

assets/styles/_adminIndex.scss
templates/actuality/show.html.twig

S05US77 crud show banniere

---

assets/styles/carrousel.scss
templates/components/_blocVideo.html.twig
templates/components/_thumbnailPremium.html.twig

Fix preview premium on carrousel and hover lock to login

---

config/packages/vich_uploader.yaml

Fix vich uploader

---

templates/login/index.html.twig
templates/registration/register.html.twig

FIX size of inputs

---

config/packages/vich_uploader.yaml
migrations/Version20230130110400.php
src/Entity/Advertisement.php
src/Form/AdvertisementType.php

S05US79 - Upload for ads

---

assets/styles/_adminIndex.scss
config/packages/vich_uploader.yaml
migrations/Version20230130112037.php
src/Entity/Actuality.php
src/Form/ActualityType.php
templates/actuality/index.html.twig
templates/ad/index.html.twig
templates/adminVideo/index.html.twig
templates/admin_sponsor/index.html.twig
templates/admin_sponsor/show.html.twig

S05US78 upload banniere

---

templates/adminVideo/_form.html.twig
templates/adminVideo/edit.html.twig
templates/adminVideo/index.html.twig
templates/adminVideo/show.html.twig

FIX - Buttons in Admin Video

---

templates/components/_footer.html.twig

FIX link favorite if not connected

---

templates/actuality/edit.html.twig
templates/actuality/index.html.twig
templates/ad/edit.html.twig
templates/ad/index.html.twig
templates/adminVideo/edit.html.twig
templates/adminVideo/index.html.twig
templates/admin_cat/edit.html.twig
templates/admin_cat/index.html.twig
templates/admin_sponsor/edit.html.twig
templates/admin_sponsor/index.html.twig

The edit buttons are now outlined
Close #360

Buttons outline

---

assets/styles/_home.scss

Fix add margin top for empty condition of banniere

---

assets/styles/showVideo.scss
src/Controller/VideoController.php
templates/video/index.html.twig

Fix resize and condition when empty

---

templates/adminVideo/index.html.twig

Mixed premium and public - now fixed

---

assets/styles/_flash_messages.scss
src/Controller/ActualityController.php
src/Controller/AdController.php
src/Controller/AdminCatController.php
src/Controller/AdminSponsorController.php
src/Controller/AdminVideoController.php
templates/components/_flash_messages.html.twig

Fix flash message component

---

src/Entity/Video.php

Now you can't put negative numbers in duration
Close #454

Positive duration
